### ISSUE TITLE
Make the fib function faster

### ISSUE THREAD

**Issue by osmium-dev-old** [Shuvro-d/Dynamic.Programming#4]
# Problem
The fib function time complexity is O(n) but I want to make it O(Log n)

# How
Using the Fibonacci nth term formula : 
```
if n is postive:
   (phi^n) / sqrt(5) 
if n is negative
   ((-phi)^(-n)) / sqrt(5)
```

# Complexity 
## Time
Because of the Pow function the time complexity is Logarithmic -> O(Log n)

## Space
Constant -> O(1)

**Comment by osmium-dev-old** [comment]
May I make this change?

**Comment by Shuvro-d** [comment]
Thanks for your suggestion.  I will update it.
